"""Evidence Extraction Agent.

Reads untrusted filing sections and proposes evidence objects for a research
question. Pure logic + one LLM call: it takes typed inputs and returns a typed
ExtractionResult, and it has no tools and no database access — so even if a
filing contains injected instructions, the worst it can do is propose bad
evidence, which the verification agent then blocks.

Citation metadata (dates, accession numbers, URLs) is attached here from
trusted filing metadata, never generated by the model — a model cannot
hallucinate a value it is never asked to produce.
"""

from datetime import date

from pydantic import BaseModel, ValidationError

from app.llm.base import TASK_EXTRACT, LLMError, LLMProvider
from app.logging_config import get_logger
from app.schemas.agent_io import EvidenceItem, ExtractionResult, SectionInput, TaskType
from app.services.injection_guard import scan_for_injection

logger = get_logger(__name__)

AGENT_NAME = "evidence_extraction"
MAX_EVIDENCE_ITEMS = 6


class FilingMeta(BaseModel):
    """Trusted citation metadata for one filing, keyed by label."""

    label: str  # "current" | "previous"
    form_type: str
    filing_date: date
    accession_number: str
    source_url: str


class _RawEvidence(BaseModel):
    """What the model is allowed to produce — nothing more."""

    claim: str
    excerpt: str
    section_name: str
    filing_label: str = "current"
    confidence: float = 0.5


class EvidenceExtractionAgent:
    def __init__(self, provider: LLMProvider):
        self._provider = provider

    def run(
        self,
        question: str,
        task_type: TaskType,
        sections: list[SectionInput],
        metas: dict[str, FilingMeta],
    ) -> tuple[ExtractionResult, list[str]]:
        """Returns (result, injection_warnings)."""
        warnings: list[str] = []
        for section in sections:
            findings = scan_for_injection(section.text)
            if findings:
                warnings.append(f"{section.name}: {', '.join(findings)}")

        payload = {
            "question": question,
            "task_type": task_type.value,
            "max_items": MAX_EVIDENCE_ITEMS,
            "sections": [s.model_dump() for s in sections],
        }
        raw = self._provider.run_task(TASK_EXTRACT, payload)

        evidence: list[EvidenceItem] = []
        for entry in raw.get("evidence", [])[:MAX_EVIDENCE_ITEMS]:
            try:
                item = _RawEvidence.model_validate(entry)
            except ValidationError:
                logger.warning("Dropping malformed evidence entry from model output")
                continue
            meta = metas.get(item.filing_label)
            if meta is None:
                # The model referenced a filing we never gave it — drop it.
                logger.warning("Dropping evidence with unknown filing_label",
                               extra={"extra_fields": {"label": item.filing_label}})
                continue
            evidence.append(
                EvidenceItem(
                    claim=item.claim[:1000],
                    excerpt=item.excerpt[:2000],
                    section_name=item.section_name[:255],
                    filing_date=meta.filing_date,
                    accession_number=meta.accession_number,
                    source_url=meta.source_url,
                    confidence=max(0.0, min(1.0, item.confidence)),
                )
            )

        note = raw.get("missing_info_note")
        if not evidence and not note:
            note = "No evidence relevant to the question was found in the selected sections."
        if not isinstance(note, str | None):
            raise LLMError("missing_info_note must be a string or null")

        return ExtractionResult(evidence=evidence, missing_info_note=note), warnings
